
utils::globalVariables(c("scenario",
                         "daysOfLife",
                         "BW",
                         "BWcor",
                         "totalDMI",
                         "LiqDietAll",
                         "Value",
                         "nfc_intake_cum",
                         "starterIntake",
                         "MEfromliqDiet",
                         "liqDietIntake",
                         "aver_daily_gain",
                         "milkME",
                         "nfcCum",
                         "ADG",
                         "MEmaint",
                         "NEg",
                         "MEg",
                         "totalMPReq",
                         "reqCP",
                         "Metab. Energy (Mcal/kg)",
                         "Diet Prop. (%)",
                         "mtcars",
                         "cyl",
                         "final_body_weight",
                         "starter_intake",
                         "animal",
                         "birth_weight_kg",
                         "body_weight_kg",
                         "meanObs",
                         "meanPred",
                         "observed_bw",
                         "predicted_bw"
                         ))
